#!/bin/sh

. /lib/ramips.sh

# set the hostname to be "lichtenstein-" plus the last six hex digits of the
# device MAC address
devmac=$(cat /sys/class/net/eth0/address | awk -F':' '{ print $4 $5 $6 }')

uci -q batch <<-EOF > /dev/null
	set system.@system[0].hostname=lichtenstein-$devmac
	commit system
EOF

exit 0
