#!/bin/sh

# add ascii art
LICHTENSTEIN="    __    _      __    __                  __       _
   / /   (_)____/ /_  / /____  ____  _____/ /____  (_)___
  / /   / / ___/ __ \/ __/ _ \/ __ \/ ___/ __/ _ \/ / __ \\
 / /___/ / /__/ / / / /_/  __/ / / (__  ) /_/  __/ / / / /
/_____/_/\___/_/ /_/\__/\___/_/ /_/____/\__/\___/_/_/ /_/"

echo "$LICHTENSTEIN" > /etc/banner

# add some info
host=$(uci get system.@system[0].hostname)
uname=$(uname -rsom)

echo "---------------------------------------------------------" >> /etc/banner
echo "   Hostname: $host" >> /etc/banner
echo "     Kernel: $uname" >> /etc/banner
echo "---------------------------------------------------------" >> /etc/banner
